// Checks which optional audio files exist in /assets and writes src/audioConfig.generated.ts.
// Remotion's browser bundle can't test for file existence at render time, so we do it here.
// Files found in assets/ are copied into public/ so staticFile() can serve them.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const names = ['voiceover', 'music', 'knock'];
const found = {};
for (const n of names) {
  const src = path.join(root, 'assets', `${n}.mp3`);
  const dst = path.join(root, 'public', `${n}.mp3`);
  found[n] = fs.existsSync(src);
  if (found[n]) fs.copyFileSync(src, dst);
  else if (fs.existsSync(dst)) fs.rmSync(dst);
}
fs.writeFileSync(
  path.join(root, 'src', 'audioConfig.generated.ts'),
  `// AUTO-GENERATED by scripts/detect-audio.mjs — do not edit.\nexport const AUDIO = ${JSON.stringify(found)} as const;\n`,
);
console.log('audio tracks:', found);
